---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Backup and Snapshots"
      solveButton: false
    - name: module-02
      label: "Infrastructure Reporting"
      solveButton: false
    - name: module-03
      label: "Windows Reporting"
      solveButton: false

tabs:
  - name: aap
    url: https://control-${guid}.${domain}/
    external: false
  - name: Windows
    url: https://windows-ironrdp-${guid}.${domain}/
    external: false
  - name: Webapp-windows
    url: https://dbserver-${guid}.${domain}/
    external: false
  - name: Webapp-rhel
    url: https://node01-${guid}.${domain}/
    external: false
  - name: loadbalancer
    url: https://haproxy-${guid}.${domain}/
    external: false
